export const REQUEST_NEWS_LIST = 'REQUEST_NEWS_LIST';
export const RECEIVE_NEWS_LIST = 'RECEIVE_NEWS_LIST';
export const RECEIVE_NEWS_LIST_SUCCESS = 'RECEIVE_NEWS_LIST_SUCCESS';
export const ERROR_NEWS_LIST = 'ERROR_NEWS_LIST';
export const SET_NEWS_LIST_PAGE_NO = 'SET_NEWS_LIST_PAGE_NO';
export const SET_NEWS_LIST_PAGE_SIZE = 'SET_NEWS_LIST_PAGE_SIZE';
